#########################################################
#                                                       #
#         SYNOLOGY INTEGRATION AND MONITORING           #
#                                                       #
#https://www.home-assistant.io/integrations/synologydsm #
#########################################################
sensor:
  - platform: synologydsm
    host: !secret nas02_host 
    username: !secret nas02_user
    password: !secret nas02_password
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
      - volume_percentage_used
      - disk_smart_status
