#########################################################
#                                                       #
#             CUSTOMIZING SENSORS AND ICONS             #
#                                                       #
#########################################################
homeassistant:
  customize:
    script.spotify_music:
      friendly_name: Afspelen
      icon: mdi:play
    light.staande_lamp:
      icon: mdi:floor-lamp
    light.tradfri_driver:
      icon: mdi:book-open-page-variant
    light.achterdebank:
      icon: mdi:floor-lamp-dual
    light.schilderij:
      icon: mdi:aspect-ratio
