#########################################################
#                                                       #
#               AUTOMATIC THEME SELECTION               #
#                                                       #
#########################################################
automation:
- alias: Set my light theme
  trigger:
  action:
    service: frontend.set_theme
    data:
       name: mylight

- alias: 'Set HA theme for day and night'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if states.sun.sun.state == "above_horizon" %}
            summer_breeze
          {% else %}
            darkcyan
          {% endif %}