#########################################################
#                                                       #
#                  HUE TAP BUTTONS                      #
#                                                       #
#########################################################
automation:
- alias: "Select scenes when buton pressed"
  trigger:
    - platform: state
      entity_id: sensor.slaapkamer_schakelaar
      to: "1_click"
  action:
    - service: light.turn_off
      entity_id: light.slaapkamer

- alias: "Select scenes when buton pressed"
  trigger:
    - platform: state
      entity_id: sensor.slaapkamer_schakelaar
      to: "2_click"
    - platform: state
      entity_id: sensor.slaapkamer_schakelaar
      to: "3_click"
    - platform: state
      entity_id: sensor.slaapkamer_schakelaar
      to: "4_click"
  condition: []
  action:
  - service: scene.turn_on
    data_template:
      entity_id: >
          {% if states.sensor.slaapkamer_schakelaar.state == "1_click" %}
            scene.slaapkamer_avond
          {% elif states.sensor.slaapkamer_schakelaar.state == "2_click" %}
            scene.slaapkamer_orientatielicht
          {% elif states.sensor.slaapkamer_schakelaar.state == "3_click" %}
            scene.slaapkamer_avond
          {% elif states.sensor.slaapkamer_schakelaar.state == "4_click" %}
            scene.slaapkamer_overdag
          {% endif %}
  - service: timer.cancel
    entity_id: timer.timer_slaapkamer