
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
#
home_latitude: 00.0000
home_longitude: 00.0000
home_elevation: 0

# Various IP Addresses and hosts
default_gateway: 10.10.10.10
ziggo_modem: 10.10.10.11
unifi_cloudkey: 10.10.10.12

# MQTT Integration
mqtt_host: mqtt.host.local
mqtt_password: mqtt_password
mqtt_user: mqtt_user

# Spotify
spotify_clientid: spotify_clientid
spotify_secret: spotify_secret

# Plex
plex_token: plex_token

# Here travel
here_apikey: here_apikey

# Pi hole
pihole_host: 10.10.10.13
pihole_apikey: pihole_apikey
pihole_command_on:  "pihole_cmd_on"
pihole_command_off: "pihole_cmd_off"
pihole_command_state: "pihole_cmd_status"

# Withings
withings_clientid: withings_clientid
withings_clientsecret: withings_clientsecret

# Google Calendar
google_clientid: google_clientid
google_clientsecret: google_clientsecrets

# PVOutput
pvoutput_systemid: pvoutput_systemid
pvoutput_apikey: pvoutput_apikey

# AirVisual
airvisual_apikey: airvisual_apikey

# Unifi network & video
unifi_user: unifi_user
unifi_password: unifi_password

unifivideo_apikey: unifivideo_apikey
unifivideo_camerapassword: unifivieo_camerapassword

# Apple TV
appletv_IP: 10.10.10.14
appletv_port: appltv_port
appletv_credentials: appletv_credentials

nas02_host: 10.10.10.15
nas02_user: nas02_user
nas02_password: nas02_password

# BMW ConnectedDrive
bmw_username: bmw_username
bmw_password: bmw_password

# RDW
rdw_bmwkenteken: rdw_kenteken
rdw_peugeotkenteken: rdw_kenteken2

# Denon receiver
denon_IP: 10.10.10.16

# Luftdaten
luftdaten_sensorid: 0

# Samsung TV
samsungtv_IP: 10.10.10.17
samsungtv_mac: tv_mac

youless_host: 10.10.10.18

myfitnesspal_user: myfitnesspal_user
myfitnesspal_password: myfitnesspal_password

homeassistant_baseurl: https://my.url.local
p2000_url: https://myp2000.url.local


iframe_onshuis: iframe_url_huis
iframe_recepten: iframe_url_recepten
iframe_adblocker: iframe_url_adblocker
iframe_locaties: iframe_url_locaties


# Ping
ping_iPhoneAJ: 10.10.10.19
ping_iPhoneTineke: 10.10.10.20
ping_werktelefoonAJ: 10.10.10.21 
ping_werklaptopAJ: 10.10.10.22

# Travis CI
travis_token: "mygithubtravistoken"

# Device tracking - iCloud
icloud_user: thisisnotmyuserid@nowhere.com
icloud_password: yeahyouwouldliketoknowthat

places_api: thisistheapiuserpassword

mysql_server: mysql_server

# NS API
ns_api: NS_key

alphavantage_key: alphavantage_key

influxdb_password: homeassistant
influxdb_user: homeassistant
influxdb_db: homeassistant

# whole house audio
snapcastserver: anipaddress
mpdserver: anipaddress
