language: python
python:
  - "3.7.6"
before_install:
  - mv .travis_secrets.yaml secrets.yaml
install:
  - pip3 install feedparser geopy
  - pip3 install homeassistant
  - hass --version
script:
  - hass -c . --script check_config
