- id: '1580575473548'
  alias: turn on the lights in woonkamer when the sun is set
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: c115d99ce425428393a580370cea848c
    domain: light
    entity_id: light.staande_lamp
    type: turn_on
  - device_id: a16aee5d5b0c44b79d01f781dc28718e
    domain: light
    entity_id: light.tradfri_driver
    type: turn_on
  - device_id: 8d15223797554c19846e5d5b7164de8b
    domain: light
    entity_id: light.achterdebank
    type: turn_on
- id: '1580676841533'
  alias: Naar bed
  description: Turn things of when going to bed
  trigger: []
  condition: []
  action:
  - scene: scene.naar_bed
  - delay: 00:01:00
  - device_id: 1cdd7b07c0b64ebbaf72da61411445a7
    domain: light
    entity_id: light.erker
    type: turn_off
- id: '1580850032738'
  alias: turn on light when macbook tineke comes from screen saver
  description: ''
  trigger:
  - entity_id: binary_sensor.macbooktineke
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.bureaulamp_tineke
    service: light.turn_on
- id: '1581155917396'
  alias: Update location
  description: ''
  trigger: []
  condition: []
  action:
  - data: {}
    service: device_tracker.see
- id: '1581159296389'
  alias: Deur open in woonkamer
  description: ''
  trigger:
  - entity_id: binary_sensor.deur_woonkamer
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '5'
    condition: numeric_state
    entity_id: sensor.sensor_hal_light_level
  action:
  - entity_id: timer.timer_hal
    service: timer.start
  - entity_id: light.overloop
    service: light.turn_on
