- id: '1580575473548'
  alias: turn on the lights in woonkamer when the sun is set
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: c115d99ce425428393a580370cea848c
    domain: light
    entity_id: light.staande_lamp
    type: turn_on
  - device_id: a16aee5d5b0c44b79d01f781dc28718e
    domain: light
    entity_id: light.tradfri_driver
    type: turn_on
  - device_id: 8d15223797554c19846e5d5b7164de8b
    domain: light
    entity_id: light.achterdebank
    type: turn_on
- id: '1580676841533'
  alias: Naar bed
  description: Turn things of when going to bed
  trigger: []
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.night_mode
    service: input_boolean.turn_on
  - scene: scene.naar_bed
  - device_id: 1cdd7b07c0b64ebbaf72da61411445a7
    domain: light
    entity_id: light.erker
    type: turn_off
  - data: {}
    entity_id: media_player.ue46d6200_ue46d6200
    service: media_player.turn_off
  - data: {}
    entity_id: media_player.denon_x2100w
    service: media_player.turn_off
  - delay: 00:01:00
- id: '1580850032738'
  alias: turn on light when macbook tineke comes from screen saver
  description: ''
  trigger:
  - entity_id: binary_sensor.macbooktineke
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: light.bureaulamp_tineke
    service: light.turn_on
- id: '1581155917396'
  alias: 'Presence: Update location'
  description: 'Presence: Update location'
  trigger: []
  condition: []
  action:
  - data: {}
    service: device_tracker.see
- id: '1581159296389'
  alias: Deur open in woonkamer
  description: ''
  trigger:
  - entity_id: binary_sensor.deur_woonkamer
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '5'
    condition: numeric_state
    entity_id: sensor.sensor_hal_light_level
  action:
  - entity_id: timer.timer_hal
    service: timer.start
  - entity_id: light.overloop
    service: light.turn_on
- id: '1577895200056'
  alias: Turn on receiver when TV turns on
  description: ''
  trigger:
  - entity_id: media_player.ue46d6200_ue46d6200
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: Turn on Denon receiver
    data: {}
    entity_id: media_player.denon_x2100w
    service: media_player.turn_on
- alias: Turn on light in the hallway when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_motion_hal
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.sensor_hal_light_level
    below: 5
  action:
  - service: timer.start
    entity_id: timer.timer_hal
  - service: light.turn_on
    entity_id: light.overloop
  id: b2e0a869c141460eb6baddc2aedc459c
- alias: Turn off lights in the hallway 3 minutes after last movement
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_hal
  action:
  - service: light.turn_off
    entity_id: light.overloop
  id: a70c5289c24d4707919ef6380e8fa53d
- id: '1583700854299'
  alias: to day mode
  description: ''
  trigger:
  - entity_id: input_boolean.day_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.night_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.guest_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.quiet_mode
    service: input_boolean.turn_off
- alias: to night mode
  id: 158373aa3854299'
  description: ''
  trigger:
  - entity_id: input_boolean.night_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.day_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.guest_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.quiet_mode
    service: input_boolean.turn_off
- alias: to quiet mode
  id: 158373bb3854299'
  description: ''
  trigger:
  - entity_id: input_boolean.quiet_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.day_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.guest_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.night_mode
    service: input_boolean.turn_off
- alias: to guest mode
  id: 158373aa38542dd'
  description: ''
  trigger:
  - entity_id: input_boolean.guest_mode
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.day_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.night_mode
    service: input_boolean.turn_off
  - data: {}
    entity_id: input_boolean.quiet_mode
    service: input_boolean.turn_off
- alias: at sun rise turn off the lights in the living room
  id: 158373aa3854ee'
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: c115d99ce425428393a580370cea848c
    domain: light
    entity_id: light.staande_lamp
    type: turn_off
  - device_id: a16aee5d5b0c44b79d01f781dc28718e
    domain: light
    entity_id: light.tradfri_driver
    type: turn_off
- id: '1583878198776'
  alias: Set house to day mode
  description: ''
  trigger:
  - at: 06:20
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: input_boolean.day_mode
    service: input_boolean.turn_on
