
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
        packages: !include_dir_named packages

        latitude: !secret home_latitude
        longitude: !secret home_longitude
        elevation: !secret home_elevation
        unit_system: metric
        time_zone: "Europe/Amsterdam"
        name: Home

http:
        base_url: !secret homeassistant_baseurl 

logger:
   default: warning

api:

recorder:
  db_url: !secret mysql_server

discovery:

config:

binary_sensor:
  - platform: huesensor
device_tracker:
  - platform: huesensor
remote:
  - platform: huesensor


automation: !include automations.yaml
script: !include_dir_merge_named scripts
