
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
   packages: !include_dir_named packages

http:
        base_url: !secret homeassistant_baseurl 

logger:
   default: warning
#   logs:
#        homeassistant.components.mqtt: debug

api:

discovery:

config:

script: !include_dir_merge_named scripts
