#########################################################
#                                                       #
#                       NETWORK PING                    #
#                                                       #
#########################################################

binary_sensor:

  ##########################################################
  ## Wan Monitor
  ##########################################################

  - platform: ping
    host: 8.8.8.8
    name: WAN
    scan_interval: 60


  ##########################################################
  ## Gateway Monitor
  ##########################################################
  - platform: ping
    host: !secret default_gateway
    name: Gateway
    scan_interval: 60

  ##########################################################
  ## Ziggo Modem
  ##########################################################

  - platform: ping
    host: !secret ziggo_modem
    name: Ziggo modem
    scan_interval: 60

  ##########################################################
  ## Unifi Cloudkey
  ##########################################################
  - platform: ping
    host: !secret unifi_cloudkey
    name: Unifi Cloudkey
    scan_interval: 60    

