#########################################################
#                                                       #
#         CONFIGURATION OF SAMSUNG TV INTEGRATION       #
#                                                       #
#########################################################

automation:
  id: '1577895200056'
  alias: Turn on received when TV turns on
  description: ''
  trigger:
  - entity_id: media_player.ue46d6200_ue46d6200
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: 'Turn on Denon receiver'
    data: {}
    entity_id: media_player.denon_x2100w
    service: media_player.turn_on

