#########################################################
#                                                       #
#         CONFIGURATION OF SAMSUNG TV INTEGRATION       #
#                                                       #
#########################################################

media_player:
  - platform: samsungtv
    host: !secret samsungtv_IP
    mac: !secret samsungtv_mac

automation:
  id: '1577895200056'
  alias: Turn on received when TV turns on
  description: ''
  trigger:
  - entity_id: media_player.samsung_tv_remote
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: 'Turn on Denon receiver'
    data: {}
    entity_id: media_player.denon_x2100w
    service: media_player.turn_on

