automation:
  - alias: 'Lights on when first person arrives'
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'on'
    condition:
    - condition: numeric_state
      entity_id: sensor.sensor_hal_light_level
      below: 5
    action:
    - service: light.turn_on
      entity_id: group.thuiskomlicht
