#########################################################
#                                                       #
#             LIGHTS OF WHEN LEAVING HOME               #
#                                                       #
#########################################################
automation:
  - alias: 'Lights off when last person leaves'
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'off'
    action:
    - service: light.turn_off
      entity_id: group.all_lights
