automation:
  - alias: 'Lights on when first person arrives'
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: input_boolean.notify_home
      to: 'off'
    action:
    - service: light.turn_off
      entity_id: group.all_lights
