#########################################################
#                                                       #
#        CUSTOM INTEGRATION OF EMERGENCY SERVICES INFO  #
#                                                       #
#########################################################
sensor:
  - platform: p2000
    regios: 1,2
    disciplines: 1,2,3,4
    radius: 15000
    scan_interval: 60
