#########################################################
#                                                       #
#              UPTIME SENSORS SENSORS                   #
#                                                       #
#########################################################

sensor:
  - platform: uptime
    unit_of_measurement: minutes
