#########################################################
#                                                       #
#               LIGHTS CONTROLLED BY MQTT               #
#                                                       #
#########################################################
light:
  - platform: mqtt
    name: 'Overloop'
    state_topic: 'homeassistant/switch/hal/overloop'
    command_topic: 'homeassistant/switch/hal/overloop/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Schilderij'
    state_topic: 'homeassistant/switch/woonkamer/schilderijen'
    command_topic: 'homeassistant/switch/woonkamer/schilderijen/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Lamp voordeur'
    state_topic: 'homeassistant/switch/buiten/buitenlampVoordeur'
    command_topic: 'homeassistant/switch/buiten/buitenlampVoordeur/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Lamp achtergevel'
    state_topic: 'homeassistant/switch/buiten/buitenlampAchtergevel'
    command_topic: 'homeassistant/switch/buiten/buitenlampAchtergevel/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Lamp zijgevel'
    state_topic: 'homeassistant/switch/buiten/buitenlampZijgevel'
    command_topic: 'homeassistant/switch/buiten/buitenlampZijgevel/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Philipslamp'
    state_topic: 'homeassistant/switch/keuken/philipslamp'
    command_topic: 'homeassistant/switch/keuken/philipslamp/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: mqtt
    name: 'Bureaulamp Tineke'
    state_topic: 'homeassistant/switch/werkkamer/bureaulampTineke'
    command_topic: 'homeassistant/switch/werkkamer/bureaulampTineke/set'
    payload_on: 'on'
    payload_off: 'off'
    state_value_template: '{{ value }}'

  - platform: group
    name: buitenverlichting
    entities:
      - light.lamp_voordeur
      - light.lamp_zijgevel
      - light.lamp_achtergevel

  - platform: group
    name: halverlichting
    entities:
      - light.overloop


  - platform: group
    name: keuken
    entities:
      - light.philipslamp

  - platform: group
    name: woonkamer
    entities:
      - light.staande_lamp
      - light.tradfri_driver
      - light.achterdebank
      - light.schilderij

  - platform: group
    name: Verlichting woonkamer/keuken
    entities:
      - light.keuken
      - light.woonkamer

  - platform: group
    name: Verlichting slaapkamer
    entities:
      - light.slaapkamer_achter_kast
      - light.nachtkastje_aj
      - light.nachtkastje_tineke
      - light.bed_kant_anne_jan

  - platform: group
    name: Verlichting huis
    entities:
      - light.verlichting_woonkamer_keuken
      - light.verlichting_slaapkamer
      - light.buitenverlichting


homeassistant:
  customize:
    light.buitenverlichting:
      icon: mdi:coach-lamp

automation: 
- alias: at sun set turn on the lamp in the living room
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: c115d99ce425428393a580370cea848c
    domain: light
    entity_id: light.staande_lamp
    type: turn_on
  - device_id: a16aee5d5b0c44b79d01f781dc28718e
    domain: light
    entity_id: light.tradfri_driver
    type: turn_on

- alias: at sun rise turn off the lamp in the living room
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: c115d99ce425428393a580370cea848c
    domain: light
    entity_id: light.staande_lamp
    type: turn_off
  - device_id: a16aee5d5b0c44b79d01f781dc28718e
    domain: light
    entity_id: light.tradfri_driver
    type: turn_off
