#########################################################
#                                                       #
#                    WORKDAY SENSOR                     #
#                                                       #
#########################################################
binary_sensor:
   - platform: workday
     country: NL
