#########################################################
#                                                       #
#             MOTION RESPONSE IN THE HALLWAY            #
#                                                       #
#########################################################
automation:
- alias: Turn on test light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_hal_motion
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.sensor_hal_light_level
      below: 5
  action:
    service: light.turn_on
    entity_id: light.overloop

- alias: Turn off test light 3 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_hal_motion
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.overloop    
